# GentStore — graphical frontend for Portage
# Copyright (C) 2026  JamJan05
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Shared test fixtures.

The Qt application is created once for the whole session — a second
``QApplication`` in one process is not allowed — and it is pointed at a throwaway
configuration directory so running the tests never touches the settings or the
log of the person running them.

:func:`portage_env` is the gate in front of every test that asks this machine a
question rather than a fixture. It lives here because four modules had a copy of
it, and because the copies knew about only one of the two ways a host can fail
to be a Gentoo system.
"""

from __future__ import annotations

import os

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

import pytest  # noqa: E402

from gentstore.app import GentstoreApplication  # noqa: E402


@pytest.fixture(scope="session")
def app(tmp_path_factory: pytest.TempPathFactory) -> GentstoreApplication:
    sandbox = tmp_path_factory.mktemp("xdg")
    os.environ["XDG_CONFIG_HOME"] = str(sandbox / "config")
    os.environ["XDG_STATE_HOME"] = str(sandbox / "state")

    existing = GentstoreApplication.instance()
    return existing if isinstance(existing, GentstoreApplication) else GentstoreApplication([])


@pytest.fixture(scope="session")
def translations():
    """The compiled catalogues, or a skip — for tests that switch language.

    ``.qm`` files are build artifacts: generated by ``tools/i18n.py compile``,
    kept out of the repository by ``.gitignore``, and built before the tests
    both in CI (``tests.yml``) and in the ebuild (``python_prepare_all``). The
    one path that did not build them first was ``make check``, so a developer
    running the suite locally met two assertion failures about menu titles and
    no hint that a build step was missing.

    A skip rather than a pass. "This could not be checked" and "this was
    checked and is fine" are different answers, and the second one is not this
    fixture's to give — on a machine where the catalogues *are* built, which is
    every machine CI runs on, these tests run as they always did.
    """
    from gentstore.app import I18N_DIR, SUPPORTED_LANGUAGES  # noqa: PLC0415

    missing = [
        name for name in SUPPORTED_LANGUAGES if not (I18N_DIR / f"gentstore_{name}.qm").is_file()
    ]
    if missing:
        pytest.skip(
            "the translation catalogues are not built ("
            + ", ".join(f"gentstore_{name}.qm" for name in missing)
            + "); run `make translations`"
        )


@pytest.fixture(scope="session")
def portage_env():
    """The machine's own Portage, or a skip — for tests that ask it questions.

    Two different absences, and they look nothing alike. On a machine with no
    Gentoo on it the module is not there at all and :func:`env` raises. In CI it
    is there — ``pip install portage`` puts a working 3.0.x on any host — and
    then answers every question with nothing: no arch, no installed packages, a
    repository list built from whatever ``/etc/portage`` happens to hold. The
    first failed loudly and skipped; the second failed as ``assert 0 > 100``,
    which reads like a broken test rather than a host that has no packages.

    Both mean the same thing to a test written against a real system, so both
    skip here.
    """
    from gentstore.core.packages import installed_cps  # noqa: PLC0415 - slow import
    from gentstore.core.portage_env import PortageUnavailableError, env  # noqa: PLC0415

    try:
        environment = env()
    except PortageUnavailableError as exc:  # pragma: no cover - non-Gentoo host
        pytest.skip(f"no usable Portage installation: {exc}")

    if not environment.arch or not installed_cps(environment):  # pragma: no cover - CI
        pytest.skip(
            "Portage is importable here but describes no installed system: "
            f"arch={environment.arch!r}, repositories={environment.repo_names}"
        )
    return environment
