"""Tests for reading the messages packages leave behind.

Two storage layouts, one accumulating ``summary.log`` and one file per package,
both driven by ``PORTAGE_ELOG_SYSTEM``. The samples are copied from this
machine's real log, headers and all.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

import pytest

from gentstore.core import elog
from gentstore.core.elog import Severity

# The header line is as Portage writes it, which is longer than the line limit;
# breaking it would stop being a sample of the thing under test.
SUMMARY = (
    ">>> Messages generated by process 5454 on 2026-08-26 02:53:18 -00"
    " for package dev-libs/icu-78.3:"
) + """

QA: install
QA Notice: setuptools warnings detected:

\tLicense classifiers are deprecated.

>>> Messages generated by process 5454 on 2026-08-26 02:54:10 -00 for package sys-apps/less-679:

LOG: postinst
The mesg/wall/write tools have been disabled due to USE=-tty-helpers.

WARN: postinst
Read the news item before rebooting.

>>> Messages generated by process 9000 on 2026-08-27 10:00:00 -00 for package app-alternatives/bc-0:

ERROR: preinst
Something went wrong here.
"""


# -- parsing ----------------------------------------------------------------


def test_every_entry_is_found_with_its_package_and_time() -> None:
    entries = elog.parse_summary(SUMMARY)
    assert [item.package for item in entries] == [
        "dev-libs/icu-78.3",
        "sys-apps/less-679",
        "app-alternatives/bc-0",
    ]
    assert entries[0].when == datetime(2026, 8, 26, 2, 53, 18)


def test_an_entry_can_carry_several_blocks() -> None:
    _first, less, _bc = elog.parse_summary(SUMMARY)
    assert [block.severity for block in less.blocks] == [Severity.LOG, Severity.WARN]
    assert [block.phase for block in less.blocks] == ["postinst", "postinst"]


def test_the_worst_block_decides_how_the_entry_is_shown() -> None:
    """A note and a warning together is a warning; that is what gets skimmed."""
    _first, less, bc = elog.parse_summary(SUMMARY)
    assert less.severity is Severity.WARN
    assert bc.severity is Severity.ERROR


def test_blank_lines_around_a_block_are_trimmed() -> None:
    (icu, *_rest) = elog.parse_summary(SUMMARY)
    lines = icu.blocks[0].lines
    assert lines[0].startswith("QA Notice")
    assert lines[-1].strip()


def test_the_summary_is_the_first_line_with_something_on_it() -> None:
    (icu, *_rest) = elog.parse_summary(SUMMARY)
    assert icu.summary == "QA Notice: setuptools warnings detected:"


def test_an_empty_log_gives_no_entries() -> None:
    assert elog.parse_summary("") == ()
    assert elog.parse_summary("nothing here at all\n") == ()


def test_a_header_with_no_messages_under_it_is_dropped() -> None:
    text = ">>> Messages generated by process 1 on 2026-01-01 00:00:00 -00 for package a/b-1:\n\n"
    assert elog.parse_summary(text) == ()


@pytest.mark.parametrize(
    ("text", "expected"),
    [
        ("2026-08-26 02:53:18 -00", datetime(2026, 8, 26, 2, 53, 18)),
        ("2026-08-26 02:53:18", datetime(2026, 8, 26, 2, 53, 18)),
        ("not a date", None),
    ],
)
def test_timestamps_are_read_including_the_odd_offset(text, expected) -> None:
    """Portage writes "-00", which is not an offset strptime will take."""
    assert elog._parse_when(text) == expected


# -- the per-package layout -------------------------------------------------


def test_a_per_package_log_is_read(tmp_path: Path) -> None:
    path = tmp_path / "media-video:mpv-0.41.0:20260826-025318.log"
    path.write_text("LOG: postinst\nSomething useful.\n", encoding="utf-8")

    entry = elog.parse_package_log(path)
    assert entry is not None
    assert entry.package == "media-video/mpv-0.41.0"
    assert entry.when == datetime(2026, 8, 26, 2, 53, 18)
    assert entry.blocks[0].severity is Severity.LOG


def test_a_file_that_is_not_a_package_log_is_skipped(tmp_path: Path) -> None:
    path = tmp_path / "summary.log"
    path.write_text("LOG: postinst\nx\n", encoding="utf-8")
    assert elog.parse_package_log(path) is None


# -- loading both at once ---------------------------------------------------


def test_both_layouts_are_read_together(tmp_path: Path) -> None:
    """PORTAGE_ELOG_SYSTEM can be changed, and then both places have messages."""
    (tmp_path / "summary.log").write_text(SUMMARY, encoding="utf-8")
    (tmp_path / "app-x:y-1:20260101-000000.log").write_text(
        "WARN: setup\nOld message.\n", encoding="utf-8"
    )

    entries = elog.load(directory=tmp_path)
    packages = {item.package for item in entries}
    assert "app-x/y-1" in packages
    assert "app-alternatives/bc-0" in packages


def test_entries_come_back_newest_first(tmp_path: Path) -> None:
    (tmp_path / "summary.log").write_text(SUMMARY, encoding="utf-8")
    entries = elog.load(directory=tmp_path)
    assert entries[0].package == "app-alternatives/bc-0"


def test_a_missing_log_directory_is_simply_empty(tmp_path: Path) -> None:
    assert elog.load(directory=tmp_path / "absent") == ()


def test_only_the_tail_of_a_huge_log_is_read(tmp_path: Path, monkeypatch) -> None:
    """A multi-megabyte summary must not stall the screen it feeds."""
    monkeypatch.setattr(elog, "MAX_BYTES", 400)
    path = tmp_path / "summary.log"
    path.write_text(SUMMARY * 20, encoding="utf-8")

    entries = elog.load(directory=tmp_path)
    assert entries, "the tail still has to produce entries"
    assert len(entries) < 60, "the whole file should not have been read"
    assert all(item.package for item in entries), "no half-parsed fragment"


def test_since_picks_out_what_a_command_just_produced() -> None:
    entries = elog.parse_summary(SUMMARY)
    recent = elog.since(entries, datetime(2026, 8, 27, 0, 0, 0))
    assert [item.package for item in recent] == ["app-alternatives/bc-0"]


def test_the_worst_severity_across_a_set_is_reported() -> None:
    entries = elog.parse_summary(SUMMARY)
    assert elog.worst(entries) is Severity.ERROR
    assert elog.worst(()) is None


# -- against the real system ------------------------------------------------


def test_the_machines_own_messages_read() -> None:
    from gentstore.core.portage_env import PortageUnavailableError, env

    try:
        environment = env()
    except PortageUnavailableError as exc:  # pragma: no cover - non-Gentoo host
        pytest.skip(f"no usable Portage installation: {exc}")

    entries = elog.load(environment)
    if not entries:  # pragma: no cover - a system that has never merged anything
        pytest.skip("no elog messages on this machine")

    assert all(item.package for item in entries)
    assert all(item.blocks for item in entries)
    # Newest first, and every entry that has a time is in order.
    timed = [item.when for item in entries if item.when is not None]
    assert timed == sorted(timed, reverse=True)


def test_the_world_set_and_the_installed_list_are_different_things() -> None:
    """The whole point of the @world screen, asserted."""
    from gentstore.core import worldset
    from gentstore.core.portage_env import PortageUnavailableError, env

    try:
        environment = env()
    except PortageUnavailableError as exc:  # pragma: no cover
        pytest.skip(f"no usable Portage installation: {exc}")

    world = worldset.world_entries(environment)
    installed = worldset.installed_packages(environment)
    assert world, "an empty @world would make this meaningless"
    assert len(installed) > len(world) * 2, (
        "most of what is installed should be a dependency, not something asked for"
    )
    world_cps = {entry.cp for entry in world}
    assert world_cps.issubset({package.cp for package in installed} | world_cps)
