# GentStore — graphical frontend for Portage
# Copyright (C) 2026  JamJan05
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""What packages had to say while they were being installed.

``einfo``, ``ewarn`` and ``eerror`` in an ebuild write messages that scroll past
during a build and are gone by the time anyone reads the summary. Portage keeps
them, which is the part most people never find out — usually in one
accumulating ``elog/summary.log``, sometimes as one file per package, depending
on ``PORTAGE_ELOG_SYSTEM``. Both layouts are read here.

An entry looks like this::

    >>> Messages generated by process 5454 on 2026-08-26 02:53:18 -00
        for package dev-cpp/eigen-3.4.0-r3:

    QA: prepare
    Compatibility with CMake < 3.5 has been removed…

One package, one moment, and one or more blocks each carrying a class and the
build phase it came from. The class is what decides the colour, and it is the
difference between "this package left you a note" and "this package failed a
check somebody should look at".
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from datetime import datetime
from enum import StrEnum
from pathlib import Path

from .portage_env import PortageEnv

log = logging.getLogger(__name__)

DEFAULT_LOG_DIR = Path("/var/log/portage")

#: Reading the tail of a very long summary is enough; the interesting messages
#: are the recent ones, and a multi-megabyte file should not stall the screen.
MAX_BYTES = 4 * 1024 * 1024

_HEADER = re.compile(
    r"^>>> Messages generated by process (?P<pid>\d+) on (?P<when>.+?) "
    r"for package (?P<package>\S+?):?$"
)
_BLOCK = re.compile(r"^(?P<severity>[A-Z]+): (?P<phase>\S+)\s*$")

#: ``media-video:mpv-0.41.0:20260826-025318.log`` — the per-package layout.
_PACKAGE_LOG = re.compile(r"^(?P<category>[^:]+):(?P<package>[^:]+):(?P<stamp>[^.]+)\.log$")


class Severity(StrEnum):
    """Portage's own message classes, in the order they deserve attention."""

    ERROR = "error"
    WARN = "warn"
    QA = "qa"
    LOG = "log"
    INFO = "info"

    @property
    def rank(self) -> int:
        return list(Severity).index(self)


_SEVERITIES = {
    "ERROR": Severity.ERROR,
    "WARN": Severity.WARN,
    "QA": Severity.QA,
    "LOG": Severity.LOG,
    "INFO": Severity.INFO,
}


@dataclass(frozen=True, slots=True)
class ElogBlock:
    """One class of message from one build phase."""

    severity: Severity
    phase: str
    lines: tuple[str, ...]

    @property
    def text(self) -> str:
        return "\n".join(self.lines)


@dataclass(frozen=True, slots=True)
class ElogEntry:
    """Everything one package said during one merge."""

    package: str
    when: datetime | None
    blocks: tuple[ElogBlock, ...]
    source: Path | None = None

    @property
    def cp(self) -> str:
        from portage.versions import cpv_getkey  # noqa: PLC0415 — slow import

        return cpv_getkey(self.package) or self.package

    @property
    def severity(self) -> Severity:
        """The worst thing in the entry — what the list shows beside it."""
        return min(
            (block.severity for block in self.blocks),
            key=lambda item: item.rank,
            default=Severity.LOG,
        )

    @property
    def summary(self) -> str:
        """The first line with something on it, for a one-line list."""
        for block in self.blocks:
            for line in block.lines:
                if line.strip():
                    return " ".join(line.split())
        return ""

    @property
    def text(self) -> str:
        return "\n\n".join(f"{block.severity.value}: {block.phase}\n{block.text}"
                           for block in self.blocks)


def _parse_when(text: str) -> datetime | None:
    """``2026-08-26 02:53:18 -00`` — the offset is not always a real one."""
    cleaned = " ".join(text.split())
    for pattern in ("%Y-%m-%d %H:%M:%S %z", "%Y-%m-%d %H:%M:%S", "%a %b %d %H:%M:%S %Y"):
        try:
            return datetime.strptime(cleaned, pattern).replace(tzinfo=None)
        except ValueError:
            continue
    # A "-00" offset is not something strptime accepts; drop the last word.
    head = cleaned.rsplit(" ", 1)[0]
    try:
        return datetime.strptime(head, "%Y-%m-%d %H:%M:%S")
    except ValueError:
        return None


def _blocks(lines: list[str]) -> tuple[ElogBlock, ...]:
    blocks: list[ElogBlock] = []
    severity = Severity.LOG
    phase = ""
    collected: list[str] = []

    def flush() -> None:
        if collected and any(line.strip() for line in collected):
            blocks.append(
                ElogBlock(severity=severity, phase=phase, lines=tuple(_trim(collected)))
            )

    for line in lines:
        match = _BLOCK.match(line)
        if match and match.group("severity") in _SEVERITIES:
            flush()
            severity = _SEVERITIES[match.group("severity")]
            phase = match.group("phase")
            collected = []
            continue
        collected.append(line)
    flush()
    return tuple(blocks)


def _trim(lines: list[str]) -> list[str]:
    start, end = 0, len(lines)
    while start < end and not lines[start].strip():
        start += 1
    while end > start and not lines[end - 1].strip():
        end -= 1
    return [line.rstrip() for line in lines[start:end]]


def parse_summary(text: str, source: Path | None = None) -> tuple[ElogEntry, ...]:
    """Split an accumulating ``summary.log`` into entries, newest last."""
    entries: list[ElogEntry] = []
    package = ""
    when: datetime | None = None
    collected: list[str] = []

    def flush() -> None:
        if not package:
            return
        blocks = _blocks(collected)
        if blocks:
            entries.append(
                ElogEntry(package=package, when=when, blocks=blocks, source=source)
            )

    for line in text.splitlines():
        match = _HEADER.match(line)
        if match:
            flush()
            package = match.group("package")
            when = _parse_when(match.group("when"))
            collected = []
            continue
        collected.append(line)
    flush()
    return tuple(entries)


def parse_package_log(path: Path) -> ElogEntry | None:
    """One file from the per-package ``save`` layout."""
    match = _PACKAGE_LOG.match(path.name)
    if match is None:
        return None
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:  # pragma: no cover - a log we cannot read
        return None

    blocks = _blocks(text.splitlines())
    if not blocks:
        return None
    try:
        when = datetime.strptime(match.group("stamp"), "%Y%m%d-%H%M%S")
    except ValueError:
        when = None
    return ElogEntry(
        package=f"{match.group('category')}/{match.group('package')}",
        when=when,
        blocks=blocks,
        source=path,
    )


def log_dir(env: PortageEnv | None = None) -> Path:
    """Where Portage keeps its logs, honouring ``PORTAGE_LOGDIR``."""
    if env is None:
        return DEFAULT_LOG_DIR
    configured = env.settings.get("PORTAGE_LOGDIR") or env.settings.get("PORT_LOGDIR")
    return Path(configured) if configured else DEFAULT_LOG_DIR


def _read_tail(path: Path) -> str:
    """The whole file, or its last few megabytes if it has grown unreasonable."""
    try:
        size = path.stat().st_size
        with path.open("r", encoding="utf-8", errors="replace") as stream:
            if size > MAX_BYTES:
                stream.seek(size - MAX_BYTES)
                # The first entry is now cut in half; drop everything before the
                # next header rather than showing a fragment.
                text = stream.read()
                marker = text.find(">>> Messages generated by")
                return text[marker:] if marker >= 0 else ""
            return stream.read()
    except OSError:
        return ""


def load(env: PortageEnv | None = None, directory: Path | None = None) -> tuple[ElogEntry, ...]:
    """Every message on this system, newest first.

    Both storage layouts at once: ``PORTAGE_ELOG_SYSTEM`` can be changed at any
    time, and a system that has used both has messages in both places.
    """
    base = directory if directory is not None else log_dir(env or None) / "elog"
    entries: list[ElogEntry] = []

    summary = base / "summary.log"
    if summary.is_file():
        entries.extend(parse_summary(_read_tail(summary), summary))

    try:
        for item in base.iterdir():
            if item.is_file() and item.name != "summary.log":
                entry = parse_package_log(item)
                if entry is not None:
                    entries.append(entry)
    except OSError:
        pass

    entries.sort(key=lambda item: (item.when or datetime.min), reverse=True)
    return tuple(entries)


def since(entries: tuple[ElogEntry, ...], moment: datetime) -> tuple[ElogEntry, ...]:
    """Entries written after *moment* — what a command just produced."""
    return tuple(item for item in entries if item.when is not None and item.when >= moment)


def worst(entries: tuple[ElogEntry, ...]) -> Severity | None:
    if not entries:
        return None
    return min((item.severity for item in entries), key=lambda item: item.rank)
