#!/usr/bin/env bash
# Republish the `overlay` branch — the one Portage syncs from.
#
#     packaging/publish-overlay.sh              show what would change
#     packaging/publish-overlay.sh --push       write it and push
#
# Portage syncing a git repository treats its root as the repository root, so
# it wants `app-portage/gentstore/` and `metadata/` at the top level. This tree
# keeps them under `packaging/` instead, because a repository whose root is an
# overlay cannot also hold the application. An orphan branch is how both live in
# one place: `main` is the source, `overlay` is what Portage clones.
#
# The branch is generated, never edited. Run this after changing an ebuild or
# the Manifest, and the two can never drift — which is the whole point, because
# an overlay serving an ebuild that no longer matches the source is a bug nobody
# sees until a build fails.
#
# No release step needs this: the live ebuild builds from `main` through git-r3
# regardless. It is the *ebuild itself* reaching users that this publishes.

set -euo pipefail

BRANCH="overlay"
REPO_NAME="gentstore"
ATOM="app-portage/gentstore"

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${ROOT}/packaging/${ATOM}"

PUSH=false
[[ ${1:-} == --push ]] && PUSH=true

say()  { printf '  %s\n' "$*"; }
step() { printf '\n\033[1m%s\033[0m\n' "$*"; }

[[ -d ${SRC} ]] || { echo "No ${SRC} — run this from the repository." >&2; exit 1; }

step "Building the overlay tree"
WORK="$(mktemp -d)"
trap 'rm -rf -- "${WORK}"' EXIT

mkdir -p "${WORK}/metadata" "${WORK}/profiles" "${WORK}/${ATOM}"

# masters = gentoo, because every eclass the ebuilds inherit lives there.
cat > "${WORK}/metadata/layout.conf" <<-'EOF'
	masters = gentoo
	thin-manifests = true
	sign-commits = false
	sign-manifests = false
	# Generated by packaging/publish-overlay.sh — do not edit this branch by
	# hand. The source of truth is packaging/ on main.
EOF
echo "${REPO_NAME}" > "${WORK}/profiles/repo_name"
say "metadata/layout.conf, profiles/repo_name"

for f in "${SRC}"/*.ebuild "${SRC}/metadata.xml" "${SRC}/Manifest"; do
	[[ -e ${f} ]] || continue
	cp "${f}" "${WORK}/${ATOM}/"
	say "$(basename "${f}")"
done

# A release ebuild carries SRC_URI, and Portage refuses one whose distfile it
# cannot verify. Thin manifests drop the ebuild checksums, not the DIST lines.
for e in "${WORK}/${ATOM}"/*.ebuild; do
	grep -q '^SRC_URI=' "${e}" || continue
	pv="$(basename "${e}" .ebuild)"; pv="${pv#gentstore-}"
	if ! grep -q "gentstore-${pv}\.tar\.gz" "${WORK}/${ATOM}/Manifest" 2>/dev/null; then
		echo "  ${pv} has SRC_URI but no DIST line in the Manifest." >&2
		echo "  Portage would refuse it. Add the entry before publishing." >&2
		exit 1
	fi
	say "checked: ${pv} has its DIST entry"
done

step "The branch as it would be"
# Listed with find, never with git against ${ROOT}: pointing the real index at
# this directory stages the whole source tree as deleted, which is a memorable
# way to learn that --work-tree does exactly what it says.
(cd "${WORK}" && find . -type f | sed 's|^\./|    |' | sort)

if ! ${PUSH}; then
	printf '\nNothing written. Re-run with --push to publish it.\n'
	exit 0
fi

step "Publishing ${BRANCH}"
TMPGIT="${WORK}/.git-overlay"
git init -q --initial-branch="${BRANCH}" "${WORK}"
git -C "${WORK}" add -A
git -C "${WORK}" -c user.name="$(git -C "${ROOT}" config user.name)" \
	-c user.email="$(git -C "${ROOT}" config user.email)" \
	commit -q -m "overlay: $(git -C "${ROOT}" describe --tags --always)

Generated from packaging/ by publish-overlay.sh. Do not edit by hand."
origin="$(git -C "${ROOT}" remote get-url origin)"
git -C "${WORK}" push -q --force "${origin}" "${BRANCH}:${BRANCH}"
say "pushed ${BRANCH} to ${origin}"
rm -rf -- "${TMPGIT}"

cat <<-EOF

	Done. Portage clones that branch, so a user who has synced once gets every
	later ebuild with an ordinary "emerge --sync".
EOF
